loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/components/builders]
    modules: ["answer_builder", "prompt_builder", "dynamic_prompt_builder", "dynamic_chat_prompt_builder"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmePreviewRenderer
  excerpt: Extract the output of a Generator to an Answer format, and build prompts.
  category_slug: haystack-classes
  title: Builder API
  slug: builder-api
  order: 5
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: builder_api.md
