loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../../../haystack/components/classifiers]
    modules: ["document_language_classifier"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmePreviewRenderer
  excerpt: Detects the language of the Documents and adds it to the metadata.
  category_slug: haystack-api
  title: Classifiers
  slug: classifiers-api
  order: 10
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: classifiers_api.md
