loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/components/converters]
    modules: ["azure", "html", "markdown", "pypdf", "tika", "txt"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmePreviewRenderer
  excerpt: Extracts text from files in different formats and converts it into a unified Document format.
  category_slug: haystack-classes
  title: Converter API
  slug: converter-api
  order: 20
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: converter_api.md
