loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/dataclasses]
    modules: ["answer", "byte_stream", "chat_message", "document", "streaming_chunk"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmePreviewRenderer
  excerpt: Core classes that carry data through the system.
  category_slug: haystack-classes
  title: Data Classes API
  slug: data-classes-api
  order: 30
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: data_classes_api.md
