loaders:
  - type: python
    search_path: [../../../haystack/nodes/doc_language_classifier]
    modules: ["base", "langdetect", "transformers"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmeRenderer
  excerpt: Detects the language of the Documents
  category_slug: haystack-classes
  title: Document Language Classifier API
  slug: doc-language-classifier-api
  order: 25
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: doc_language_classifier_api.md
