loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/components/others]
    modules: ["multiplexer"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmePreviewRenderer
  excerpt: Other utility components for Haystack Pipelines.
  category_slug: haystack-classes
  title: Other Components API
  slug: others
  order: 85
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: others_api.md
