loaders:
  - type: loaders.CustomPythonLoader
    search_path: [../../../haystack/components/audio]
    modules: ["whisper_local", "whisper_remote"]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: smart
  - type: crossref
renderer:
  type: renderers.ReadmePreviewRenderer
  excerpt: Transcribes audio files.
  category_slug: haystack-classes
  title: WhisperTranscriber API
  slug: whisper-transcriber-api
  order: 180
  markdown:
    descriptive_class_title: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: whisper_transcriber_api.md
