changelog:
  exclude:
    labels:
      - ignore-for-release-notes
      - Proposal
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: Pipeline
      labels:
        - topic:pipeline
        - topic:DPR
        - topic:reader
        - topic:retriever
        - topic:tableQA
        - topic:file_converter
        - topic:preprocessing
        - topic:crawler
        - topic:images
        - topic:audio
        - topic:eval
        - topic:other_nodes
    - title: Models
      labels:
        - topic:models
    - title: DocumentStores
      labels:
        - topic:document_store
        - topic:elasticsearch
        - topic:faiss
        - topic:milvus
        - topic:weaviate
        - topic:pinecone
        - topic:sql
        - topic:knowledge_graph
        - topic:graphdb
    - title: REST API
      labels:
        - topic:api
    - title: UI / Demo
      labels:
        - topic:ui
    - title: Documentation
      labels:
        - type:documentation
    - title: Tutorials
      labels:
        - topic:tutorials
    - title: Other Changes
      labels:
        - "*"
