changelog:
  exclude:
    labels:
      - ignore-for-release-notes
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: Pipeline
      labels:
        - topic:pipeline
    - title: Models
      labels:
        - topic:models
    - title: DocumentStores
      labels:
        - topic:document_store
        - topic:elasticsearch
        - topic:faiss
        - topic:milvus
        - topic:weaviate
        - topic:pinecone
        - topic:sql
    - title: REST API
      labels:
        - topic:api
    - title: UI / Demo
      labels:
        - topic:ui
    - title: Documentation
      labels:
        - type:documentation
    - title: Tutorials
      labels:
        - type:tutorial
    - title: Other Changes
      labels:
        - "*"
