changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠 
      labels:
        - breaking change
    - title: Models
      labels:
        - topic:models
    - title: REST API
      labels:
        - topic:api
    - title: DocumentStores
      labels:
        - topic:document_store
        - topic:elasticsearch
        - topic:faiss
        - topic:sql
    - title: Documentation
      labels:
        - topic:documentation
    - title: ui
      labels:
        - topic:ui
    - title: Other Changes
      labels:
        - "*"
