FROM python:3.7.4-stretch

WORKDIR /home/user

RUN apt-get update && apt-get install -y curl git pkg-config cmake

# copy code
COPY frontend /home/user/

# install as a package
COPY frontend/requirements.txt /home/user/
RUN pip install -r requirements.txt
RUN pip install -e .

EXPOSE 8501

# cmd for running the API
CMD ["streamlit", "run", "webapp.py"]
