FROM nvidia/cuda:11.3.1-runtime-ubuntu20.04

WORKDIR /home/user

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install software dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        poppler-utils \
        git \
        python3-pip \
        python3.8 \
        python3.8-distutils \
        swig && \
    # Cleanup apt cache
    rm -rf /var/lib/apt/lists/*

# Copy Haystack package files but not the source code
COPY setup.py setup.cfg pyproject.toml VERSION.txt LICENSE README.md /home/user/

# Install all the dependencies
RUN pip3 install --upgrade --no-cache-dir pip && \
    pip3 install --no-cache-dir . && \
    # Install PyTorch with CUDA 11
    pip3 install --no-cache-dir torch==1.10.2+cu113 -f https://download.pytorch.org/whl/torch_stable.html

# Copy Haystack source code
COPY haystack /home/user/haystack/
# Install Haystack
RUN pip3 install --no-cache-dir --no-deps . && \
    # Cleanup copied files after installation is completed
    rm -rf /home/user/*
