headerPath = "license-header.txt"

excludes = [
    "*.csv",
    "*.feature",
    "*.html",
    "*.ini",
    "*.jinja2",
    "*.md",
    "*.mp3",
    "*.msg",
    "*.toml",
    "*.txt",
    "*.typed",
    "*.wav",
    "*.yaml",
    "*.yml",
    ".github",
    "CITATION.cff",
    "docker",
    "docs",
    "examples",
    "proposals",
    "releasenotes",
]

[properties]
inceptionYear = 2022
copyrightOwner = "deepset GmbH <info@deepset.ai>"
