site_name: Canals
site_url: https://deepset-ai.github.io/canals/

plugins:
  - mkdocstrings
theme:
  name: material

nav:
    - Get Started: index.md
    - Basic Concepts: concepts.md
    - How-Tos:
      - Component: how-tos/component.md
    - API Docs:
      - Component: api-docs/component.md
      - Pipeline: api-docs/pipeline.md
