from haystack.classifier.document_classifier.base import BaseClassifier
from haystack.classifier.document_classifier.farm import FARMClassifier
from haystack.classifier.query_classifier.sklearn import SklearnQueryClassifier
from haystack.classifier.query_classifier.transformers import TransformersQueryClassifier