# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

from typing import Any
from unittest.mock import ANY

import numpy as np
import pytest

from haystack import Document, component
from haystack.components.embedders import SentenceTransformersDocumentEmbedder, SentenceTransformersTextEmbedder
from haystack.components.retrievers import InMemoryEmbeddingRetriever, QueryEmbeddingRetriever
from haystack.components.writers import DocumentWriter
from haystack.document_stores.in_memory import InMemoryDocumentStore
from haystack.document_stores.types import DuplicatePolicy


@component
class MockQueryEmbedder:
    @component.output_types(embedding=list[float])
    def run(self, text: str) -> dict[str, list[float]]:
        return {"embedding": np.ones(384).tolist()}


class TestQueryEmbeddingRetriever:
    @pytest.fixture
    def sample_documents(self):
        return [
            Document(content="Renewable energy is energy that is collected from renewable resources."),
            Document(content="Solar energy is a type of green energy that is harnessed from the sun."),
            Document(content="Wind energy is another type of green energy that is generated by wind turbines."),
            Document(content="Geothermal energy is heat that comes from the sub-surface of the earth."),
            Document(content="Fossil fuels, such as coal, oil, and natural gas, are non-renewable energy sources."),
        ]

    @pytest.fixture
    def document_store_with_embeddings(self, sample_documents):
        """Create a document store populated with embedded documents."""
        document_store = InMemoryDocumentStore()
        doc_embedder = SentenceTransformersDocumentEmbedder(model="sentence-transformers/all-MiniLM-L6-v2")
        doc_writer = DocumentWriter(document_store=document_store, policy=DuplicatePolicy.SKIP)

        embedded_docs = doc_embedder.run(sample_documents)["documents"]
        doc_writer.run(documents=embedded_docs)
        return document_store

    def test_init(self):
        embedding_retriever = InMemoryEmbeddingRetriever(document_store=InMemoryDocumentStore())
        query_embedder = MockQueryEmbedder()
        retriever = QueryEmbeddingRetriever(retriever=embedding_retriever, query_embedder=query_embedder)
        assert retriever.retriever == embedding_retriever
        assert retriever.query_embedder == query_embedder

    def test_run_with_empty_document_store(self):
        retriever = QueryEmbeddingRetriever(
            retriever=InMemoryEmbeddingRetriever(document_store=InMemoryDocumentStore()),
            query_embedder=MockQueryEmbedder(),
        )
        result = retriever.run(query="green energy")
        assert "documents" in result
        assert result["documents"] == []

    def test_run_returns_documents_sorted_by_score(self):
        doc_high = Document(content="Solar energy", id="doc1", score=0.9)
        doc_low = Document(content="Fossil fuels", id="doc2", score=0.3)
        doc_mid = Document(content="Wind energy", id="doc3", score=0.6)

        @component
        class MockRetriever:
            @component.output_types(documents=list[Document])
            def run(
                self, query_embedding: list[float], filters: dict[str, Any] | None = None, top_k: int | None = None
            ) -> dict[str, list[Document]]:
                return {"documents": [doc_low, doc_high, doc_mid]}

        retriever = QueryEmbeddingRetriever(retriever=MockRetriever(), query_embedder=MockQueryEmbedder())
        result = retriever.run(query="energy")

        scores = [doc.score for doc in result["documents"]]
        assert scores == sorted(scores, reverse=True)

    def test_to_dict(self):
        retriever = QueryEmbeddingRetriever(
            retriever=InMemoryEmbeddingRetriever(document_store=InMemoryDocumentStore()),
            query_embedder=MockQueryEmbedder(),
        )
        result = retriever.to_dict()
        assert result == {
            "type": "haystack.components.retrievers.query_embedding_retriever.QueryEmbeddingRetriever",
            "init_parameters": {
                "retriever": {
                    "type": "haystack.components.retrievers.in_memory.embedding_retriever.InMemoryEmbeddingRetriever",
                    "init_parameters": {
                        "document_store": {
                            "type": "haystack.document_stores.in_memory.document_store.InMemoryDocumentStore",
                            "init_parameters": {
                                "bm25_tokenization_regex": "(?u)\\b\\w+\\b",
                                "bm25_algorithm": "BM25L",
                                "bm25_parameters": {},
                                "embedding_similarity_function": "dot_product",
                                "index": ANY,
                                "return_embedding": True,
                            },
                        },
                        "filters": None,
                        "top_k": 10,
                        "scale_score": False,
                        "return_embedding": False,
                        "filter_policy": "replace",
                    },
                },
                "query_embedder": {
                    "type": "retrievers.test_query_embedding_retriever.MockQueryEmbedder",
                    "init_parameters": {},
                },
            },
        }

    def test_from_dict(self):
        data = {
            "type": "haystack.components.retrievers.query_embedding_retriever.QueryEmbeddingRetriever",
            "init_parameters": {
                "retriever": {
                    "type": "haystack.components.retrievers.in_memory.embedding_retriever.InMemoryEmbeddingRetriever",
                    "init_parameters": {
                        "document_store": {
                            "type": "haystack.document_stores.in_memory.document_store.InMemoryDocumentStore",
                            "init_parameters": {
                                "bm25_tokenization_regex": "(?u)\\b\\w\\w+\\b",
                                "bm25_algorithm": "BM25L",
                                "bm25_parameters": {},
                                "embedding_similarity_function": "dot_product",
                                "index": "4bb5369d-779f-487b-9c16-3c40f503438b",
                                "return_embedding": True,
                            },
                        },
                        "filters": None,
                        "top_k": 10,
                        "scale_score": False,
                        "return_embedding": False,
                        "filter_policy": "replace",
                    },
                },
                "query_embedder": {
                    "type": "haystack.components.embedders.sentence_transformers_text_embedder.SentenceTransformersTextEmbedder",  # noqa E501
                    "init_parameters": {
                        "model": "sentence-transformers/all-MiniLM-L6-v2",
                        "token": {"type": "env_var", "env_vars": ["HF_API_TOKEN", "HF_TOKEN"], "strict": False},
                        "prefix": "",
                        "suffix": "",
                        "batch_size": 32,
                        "progress_bar": True,
                        "normalize_embeddings": False,
                        "trust_remote_code": False,
                        "local_files_only": False,
                        "truncate_dim": None,
                        "model_kwargs": None,
                        "tokenizer_kwargs": None,
                        "config_kwargs": None,
                        "precision": "float32",
                        "encode_kwargs": None,
                        "backend": "torch",
                    },
                },
            },
        }
        result = QueryEmbeddingRetriever.from_dict(data)
        assert isinstance(result, QueryEmbeddingRetriever)
        assert isinstance(result.retriever, InMemoryEmbeddingRetriever)
        assert isinstance(result.query_embedder, SentenceTransformersTextEmbedder)

    @pytest.mark.integration
    @pytest.mark.slow
    def test_run_with_filters(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = QueryEmbeddingRetriever(
            retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
            query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
        )
        result = retriever.run(query="energy", filters={"field": "meta.category", "operator": "==", "value": "solar"})
        assert "documents" in result
        assert all(doc.meta.get("category") == "solar" for doc in result["documents"])

    @pytest.mark.integration
    @pytest.mark.slow
    def test_run_with_top_k(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = QueryEmbeddingRetriever(
            retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
            query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
        )
        result = retriever.run(query="energy", top_k=2)
        assert "documents" in result
        assert len(result["documents"]) <= 2
