# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

from typing import Any
from unittest.mock import ANY

import pytest

from haystack import Document, component
from haystack.components.embedders import SentenceTransformersDocumentEmbedder, SentenceTransformersTextEmbedder
from haystack.components.retrievers import (
    InMemoryBM25Retriever,
    InMemoryEmbeddingRetriever,
    MultiRetriever,
    QueryEmbeddingRetriever,
)
from haystack.components.writers import DocumentWriter
from haystack.document_stores.in_memory import InMemoryDocumentStore
from haystack.document_stores.types import DuplicatePolicy


@component
class MockRetriever:
    @component.output_types(documents=list[Document])
    def run(
        self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None
    ) -> dict[str, list[Document]]:
        return {"documents": []}


@component
class RetrieverA:
    def __init__(self, documents: list[Document] | None = None):
        self.documents = documents or [Document(content="Solar energy", id="doc1", score=0.9)]

    @component.output_types(documents=list[Document])
    def run(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
        return {"documents": self.documents}


@component
class RetrieverB:
    def __init__(self, documents: list[Document] | None = None):
        self.documents = documents or [Document(content="Wind energy", id="doc2", score=0.8)]

    @component.output_types(documents=list[Document])
    def run(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
        return {"documents": self.documents}


@component
class FailingRetriever:
    @component.output_types(documents=list[Document])
    def run(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
        raise RuntimeError("connection error")


@pytest.fixture
def sample_documents():
    return [
        Document(
            content="Renewable energy is energy that is collected from renewable resources.",
            meta={"category": "renewable"},
        ),
        Document(
            content="Solar energy is a type of green energy that is harnessed from the sun.", meta={"category": "solar"}
        ),
        Document(
            content="Wind energy is another type of green energy that is generated by wind turbines.",
            meta={"category": "wind"},
        ),
        Document(
            content="Geothermal energy is heat that comes from the sub-surface of the earth.",
            meta={"category": "geothermal"},
        ),
        Document(
            content="Fossil fuels, such as coal, oil, and natural gas, are non-renewable energy sources.",
            meta={"category": "fossil"},
        ),
    ]


@pytest.fixture
def document_store_with_embeddings(sample_documents):
    """Create a document store populated with embedded documents."""
    document_store = InMemoryDocumentStore()
    doc_embedder = SentenceTransformersDocumentEmbedder(model="sentence-transformers/all-MiniLM-L6-v2")
    doc_writer = DocumentWriter(document_store=document_store, policy=DuplicatePolicy.SKIP)
    embedded_docs = doc_embedder.run(sample_documents)["documents"]
    doc_writer.run(documents=embedded_docs)
    return document_store


class TestMultiRetriever:
    def test_init_default_parameters(self):
        retrievers = {"mock": MockRetriever()}
        retriever = MultiRetriever(retrievers=retrievers)
        assert retriever.retrievers == retrievers
        assert retriever.filters is None
        assert retriever.top_k == 10
        assert retriever.max_workers == 4

    def test_init_custom_parameters(self):
        retrievers = {"mock": MockRetriever()}
        retriever = MultiRetriever(retrievers=retrievers, filters={"field": "meta.category"}, top_k=5, max_workers=2)
        assert retriever.retrievers == retrievers
        assert retriever.filters == {"field": "meta.category"}
        assert retriever.top_k == 5
        assert retriever.max_workers == 2

    def test_run_with_empty_document_store(self):
        retriever = MultiRetriever(retrievers={"mock": MockRetriever()})
        result = retriever.run(query="green energy")
        assert "documents" in result
        assert result["documents"] == []

    def test_run_combines_results_from_multiple_retrievers(self):
        retriever = MultiRetriever(retrievers={"a": RetrieverA(), "b": RetrieverB()}, max_workers=2)
        result = retriever.run(query="energy")

        assert len(result["documents"]) == 2
        assert {doc.id for doc in result["documents"]} == {"doc1", "doc2"}

    def test_run_deduplicates_results(self):
        doc1 = Document(content="Solar energy is renewable", id="doc1", score=0.9)
        doc1_duplicate = Document(content="Solar energy is renewable", id="doc1", score=0.7)
        doc2 = Document(content="Wind energy is clean", id="doc2", score=0.8)

        retriever = MultiRetriever(
            retrievers={"c": RetrieverA(documents=[doc1, doc2]), "d": RetrieverB(documents=[doc1_duplicate])},
            max_workers=2,
        )
        result = retriever.run(query="energy")

        assert len(result["documents"]) == 2
        ids = [doc.id for doc in result["documents"]]
        assert ids.count("doc1") == 1

    def test_run_resolves_filters_and_top_k(self):
        received: dict = {}

        @component
        class CapturingRetriever:
            @component.output_types(documents=list[Document])
            def run(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
                received["filters"] = filters
                received["top_k"] = top_k
                return {"documents": []}

        retriever = MultiRetriever(
            retrievers={"capturing": CapturingRetriever()}, filters={"field": "meta.category"}, top_k=5
        )

        # Should use init-time values when not overridden
        retriever.run(query="energy")
        assert received["filters"] == {"field": "meta.category"}
        assert received["top_k"] == 5

        # Should prefer run-time values when provided
        retriever.run(query="energy", filters={"field": "meta.other"}, top_k=2)
        assert received["filters"] == {"field": "meta.other"}
        assert received["top_k"] == 2

    def test_run_with_active_retrievers(self):
        retriever = MultiRetriever(retrievers={"a": RetrieverA(), "b": RetrieverB()}, max_workers=2)

        # Only run retriever "a"
        result = retriever.run(query="energy", active_retrievers=["a"])
        assert len(result["documents"]) == 1
        assert result["documents"][0].id == "doc1"

    def test_run_with_unknown_active_retriever_raises(self):
        retriever = MultiRetriever(retrievers={"mock": MockRetriever()})
        with pytest.raises(ValueError, match="Unknown retriever name"):
            retriever.run(query="energy", active_retrievers=["nonexistent"])

    def test_run_retriever_failure_raises_with_name(self):
        retriever = MultiRetriever(retrievers={"failing": FailingRetriever()})
        with pytest.raises(RuntimeError, match="Retriever 'failing' failed"):
            retriever.run(query="energy")

    def test_to_dict(self):
        retriever = MultiRetriever(
            retrievers={"bm25": InMemoryBM25Retriever(document_store=InMemoryDocumentStore())},
            filters=None,
            top_k=5,
            max_workers=2,
        )
        result = retriever.to_dict()
        assert result == {
            "type": "haystack.components.retrievers.multi_retriever.MultiRetriever",
            "init_parameters": {
                "retrievers": {
                    "bm25": {
                        "type": "haystack.components.retrievers.in_memory.bm25_retriever.InMemoryBM25Retriever",
                        "init_parameters": {
                            "document_store": {
                                "type": "haystack.document_stores.in_memory.document_store.InMemoryDocumentStore",
                                "init_parameters": {
                                    "bm25_tokenization_regex": "(?u)\\b\\w+\\b",
                                    "bm25_algorithm": "BM25L",
                                    "bm25_parameters": {},
                                    "embedding_similarity_function": "dot_product",
                                    "index": ANY,
                                    "return_embedding": True,
                                },
                            },
                            "filters": None,
                            "top_k": 10,
                            "scale_score": False,
                            "filter_policy": "replace",
                        },
                    }
                },
                "filters": None,
                "top_k": 5,
                "max_workers": 2,
            },
        }

    def test_from_dict(self):
        data = {
            "type": "haystack.components.retrievers.multi_retriever.MultiRetriever",
            "init_parameters": {
                "retrievers": {
                    "bm25": {
                        "type": "haystack.components.retrievers.in_memory.bm25_retriever.InMemoryBM25Retriever",
                        "init_parameters": {
                            "document_store": {
                                "type": "haystack.document_stores.in_memory.document_store.InMemoryDocumentStore",
                                "init_parameters": {
                                    "bm25_tokenization_regex": "(?u)\\b\\w\\w+\\b",
                                    "bm25_algorithm": "BM25L",
                                    "bm25_parameters": {},
                                    "embedding_similarity_function": "dot_product",
                                    "index": "4bb5369d-779f-487b-9c16-3c40f503438b",
                                    "return_embedding": True,
                                },
                            },
                            "filters": None,
                            "top_k": 10,
                            "scale_score": False,
                            "filter_policy": "replace",
                        },
                    }
                },
                "filters": None,
                "top_k": 5,
                "max_workers": 2,
            },
        }
        result = MultiRetriever.from_dict(data)
        assert isinstance(result, MultiRetriever)
        assert len(result.retrievers) == 1
        assert "bm25" in result.retrievers
        assert isinstance(result.retrievers["bm25"], InMemoryBM25Retriever)
        assert result.top_k == 5
        assert result.max_workers == 2

    def test_from_dict_with_no_retrievers(self):
        data = {
            "type": "haystack.components.retrievers.multi_retriever.MultiRetriever",
            "init_parameters": {"retrievers": {}, "filters": None, "top_k": 10, "max_workers": 4},
        }
        result = MultiRetriever.from_dict(data)
        assert isinstance(result, MultiRetriever)
        assert result.retrievers == {}

    def test_from_dict_with_unknown_retriever_type_raises(self):
        data = {
            "type": "haystack.components.retrievers.multi_retriever.MultiRetriever",
            "init_parameters": {
                "retrievers": {
                    "bad": {"type": "haystack.components.retrievers.NonExistentRetriever", "init_parameters": {}}
                },
                "filters": None,
                "top_k": 10,
                "max_workers": 4,
            },
        }
        with pytest.raises(ImportError, match="Could not import class"):
            MultiRetriever.from_dict(data)

    @pytest.mark.integration
    @pytest.mark.slow
    def test_run_with_filters(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = MultiRetriever(
            retrievers={
                "bm25": InMemoryBM25Retriever(document_store=document_store_with_embeddings),
                "embedding": QueryEmbeddingRetriever(
                    retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
                    query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
                ),
            }
        )
        result = retriever.run(query="energy", filters={"field": "meta.category", "operator": "==", "value": "solar"})
        assert len(result["documents"]) == 1
        assert all(doc.meta.get("category") == "solar" for doc in result["documents"])

    @pytest.mark.integration
    @pytest.mark.slow
    def test_run_with_top_k(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = MultiRetriever(
            retrievers={
                "bm25": InMemoryBM25Retriever(document_store=document_store_with_embeddings),
                "embedding": QueryEmbeddingRetriever(
                    retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
                    query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
                ),
            }
        )
        result = retriever.run(query="energy", top_k=2)
        assert "documents" in result
        # top_k applies per retriever, so total may be up to top_k * len(retrievers) before deduplication
        assert len(result["documents"]) <= 4

    @pytest.mark.integration
    @pytest.mark.slow
    def test_run_with_active_retrievers_integration(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = MultiRetriever(
            retrievers={
                "bm25": InMemoryBM25Retriever(document_store=document_store_with_embeddings),
                "embedding": QueryEmbeddingRetriever(
                    retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
                    query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
                ),
            }
        )
        result_bm25_only = retriever.run(query="energy", active_retrievers=["bm25"])
        result_all = retriever.run(query="energy")

        # BM25-only results should be a subset of all results
        bm25_ids = {doc.id for doc in result_bm25_only["documents"]}
        all_ids = {doc.id for doc in result_all["documents"]}
        assert bm25_ids.issubset(all_ids)


class TestMultiRetrieverAsync:
    @pytest.mark.asyncio
    async def test_run_async_with_empty_results(self):
        retriever = MultiRetriever(retrievers={"mock": MockRetriever()})
        result = await retriever.run_async(query="green energy")
        assert "documents" in result
        assert result["documents"] == []

    @pytest.mark.asyncio
    async def test_run_async_combines_results_from_multiple_retrievers(self):
        retriever = MultiRetriever(retrievers={"a": RetrieverA(), "b": RetrieverB()})
        result = await retriever.run_async(query="energy")
        assert len(result["documents"]) == 2
        assert {doc.id for doc in result["documents"]} == {"doc1", "doc2"}

    @pytest.mark.asyncio
    async def test_run_async_deduplicates_results(self):
        doc1 = Document(content="Solar energy is renewable", id="doc1", score=0.9)
        doc1_duplicate = Document(content="Solar energy is renewable", id="doc1", score=0.7)
        doc2 = Document(content="Wind energy is clean", id="doc2", score=0.8)

        retriever = MultiRetriever(
            retrievers={"c": RetrieverA(documents=[doc1, doc2]), "d": RetrieverB(documents=[doc1_duplicate])}
        )
        result = await retriever.run_async(query="energy")
        assert len(result["documents"]) == 2
        assert [doc.id for doc in result["documents"]].count("doc1") == 1

    @pytest.mark.asyncio
    async def test_run_async_resolves_filters_and_top_k(self):
        received: dict = {}

        @component
        class CapturingRetriever:
            @component.output_types(documents=list[Document])
            def run(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
                received["filters"] = filters
                received["top_k"] = top_k
                return {"documents": []}

        retriever = MultiRetriever(
            retrievers={"capturing": CapturingRetriever()}, filters={"field": "meta.category"}, top_k=5
        )

        await retriever.run_async(query="energy")
        assert received["filters"] == {"field": "meta.category"}
        assert received["top_k"] == 5

        await retriever.run_async(query="energy", filters={"field": "meta.other"}, top_k=2)
        assert received["filters"] == {"field": "meta.other"}
        assert received["top_k"] == 2

    @pytest.mark.asyncio
    async def test_run_async_with_active_retrievers(self):
        retriever = MultiRetriever(retrievers={"a": RetrieverA(), "b": RetrieverB()})
        result = await retriever.run_async(query="energy", active_retrievers=["a"])
        assert len(result["documents"]) == 1
        assert result["documents"][0].id == "doc1"

    @pytest.mark.asyncio
    async def test_run_async_with_unknown_active_retriever_raises(self):
        retriever = MultiRetriever(retrievers={"mock": MockRetriever()})
        with pytest.raises(ValueError, match="Unknown retriever name"):
            await retriever.run_async(query="energy", active_retrievers=["nonexistent"])

    @pytest.mark.asyncio
    async def test_run_async_retriever_failure_raises_with_name(self):
        retriever = MultiRetriever(retrievers={"failing": FailingRetriever()})
        with pytest.raises(RuntimeError, match="Retriever 'failing' failed"):
            await retriever.run_async(query="energy")

    @pytest.mark.asyncio
    async def test_run_async_uses_run_async_on_retriever_if_available(self):
        @component
        class AsyncCapableRetriever:
            def __init__(self):
                self.used_async = False

            @component.output_types(documents=list[Document])
            def run(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
                return {"documents": []}

            @component.output_types(documents=list[Document])
            async def run_async(self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None):
                self.used_async = True
                return {"documents": [Document(content="async result", id="async1")]}

        inner = AsyncCapableRetriever()
        retriever = MultiRetriever(retrievers={"async_capable": inner})
        result = await retriever.run_async(query="energy")
        assert inner.used_async is True
        assert len(result["documents"]) == 1
        assert result["documents"][0].id == "async1"

    @pytest.mark.integration
    @pytest.mark.slow
    @pytest.mark.asyncio
    async def test_run_async_with_filters(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = MultiRetriever(
            retrievers={
                "bm25": InMemoryBM25Retriever(document_store=document_store_with_embeddings),
                "embedding": QueryEmbeddingRetriever(
                    retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
                    query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
                ),
            }
        )
        result = await retriever.run_async(
            query="energy", filters={"field": "meta.category", "operator": "==", "value": "solar"}
        )
        assert len(result["documents"]) == 1
        assert all(doc.meta.get("category") == "solar" for doc in result["documents"])

    @pytest.mark.integration
    @pytest.mark.slow
    @pytest.mark.asyncio
    async def test_run_async_with_top_k(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = MultiRetriever(
            retrievers={
                "bm25": InMemoryBM25Retriever(document_store=document_store_with_embeddings),
                "embedding": QueryEmbeddingRetriever(
                    retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
                    query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
                ),
            }
        )
        result = await retriever.run_async(query="energy", top_k=2)
        assert "documents" in result
        # top_k applies per retriever, so total may be up to top_k * len(retrievers) before deduplication
        assert len(result["documents"]) <= 4

    @pytest.mark.integration
    @pytest.mark.slow
    @pytest.mark.asyncio
    async def test_run_async_with_active_retrievers_integration(self, del_hf_env_vars, document_store_with_embeddings):
        retriever = MultiRetriever(
            retrievers={
                "bm25": InMemoryBM25Retriever(document_store=document_store_with_embeddings),
                "embedding": QueryEmbeddingRetriever(
                    retriever=InMemoryEmbeddingRetriever(document_store=document_store_with_embeddings),
                    query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
                ),
            }
        )
        result_bm25_only = await retriever.run_async(query="energy", active_retrievers=["bm25"])
        result_all = await retriever.run_async(query="energy")

        # BM25-only results should be a subset of all results
        bm25_ids = {doc.id for doc in result_bm25_only["documents"]}
        all_ids = {doc.id for doc in result_all["documents"]}
        assert bm25_ids.issubset(all_ids)
