# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

import asyncio
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any

from haystack import component, default_from_dict, default_to_dict
from haystack.components.retrievers.types.protocol import TextRetriever
from haystack.core.serialization import component_from_dict, component_to_dict, import_class_by_name
from haystack.dataclasses import Document
from haystack.utils.misc import _deduplicate_documents


@component
class MultiRetriever:
    """
    A component that runs multiple retrievers in parallel and combines their results.

    Each retriever is queried concurrently using a thread pool.
    The results are deduplicated and returned as a single list of documents.

    ### Usage example

    ```python
    from haystack import Document
    from haystack.document_stores.in_memory import InMemoryDocumentStore
    from haystack.document_stores.types import DuplicatePolicy
    from haystack.components.retrievers import InMemoryBM25Retriever, InMemoryEmbeddingRetriever
    from haystack.components.retrievers import TextEmbeddingRetriever, MultiRetriever
    from haystack.components.embedders import SentenceTransformersTextEmbedder, SentenceTransformersDocumentEmbedder
    from haystack.components.writers import DocumentWriter

    documents = [
        Document(content="Renewable energy is energy that is collected from renewable resources."),
        Document(content="Solar energy is a type of green energy that is harnessed from the sun."),
        Document(content="Wind energy is another type of green energy that is generated by wind turbines."),
    ]

    # Populate the document store
    doc_store = InMemoryDocumentStore()
    doc_embedder = SentenceTransformersDocumentEmbedder(model="sentence-transformers/all-MiniLM-L6-v2")
    doc_writer = DocumentWriter(document_store=doc_store, policy=DuplicatePolicy.SKIP)
    doc_writer.run(documents=doc_embedder.run(documents)["documents"])

    # Run the multi-retriever with all retrievers
    retriever = MultiRetriever(
        retrievers={
            "bm25": InMemoryBM25Retriever(document_store=doc_store),
            "embedding": TextEmbeddingRetriever(
                retriever=InMemoryEmbeddingRetriever(document_store=doc_store),
                text_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
            ),
        },
        top_k=3,
    )

    # Run all retrievers
    result = retriever.run(query="green energy sources")

    # Run only the BM25 retriever
    result = retriever.run(query="green energy sources", active_retrievers=["bm25"])

    for doc in result["documents"]:
        print(doc.content)
    ```
    """

    def __init__(
        self,
        *,
        retrievers: dict[str, TextRetriever],
        filters: dict[str, Any] | None = None,
        top_k: int = 10,
        max_workers: int = 4,
    ) -> None:
        """
        Create the MultiRetriever component.

        :param retrievers:
            A dictionary mapping names to retriever components to run in parallel.
        :param filters:
            A dictionary of filters to apply when retrieving documents.
        :param top_k:
            The maximum number of documents to return per retriever.
        :param max_workers:
            The maximum number of threads to use for parallel retrieval.
        """
        self.retrievers = retrievers
        self.filters = filters
        self.top_k = top_k
        self.max_workers = max_workers
        self._is_warmed_up = False

    def _resolve_retrievers(self, active_retrievers: list[str] | None) -> dict[str, TextRetriever]:
        """
        Returns the subset of retrievers to run based on the active_retrievers list.

        :param active_retrievers:
            A list of retriever names to run. If None, all retrievers are returned.

        :returns:
            A dictionary of retriever names to retriever instances.

        :raises ValueError:
            If any name in `active_retrievers` does not match a retriever name.
        """
        if active_retrievers is None:
            return self.retrievers
        unknown = set(active_retrievers) - self.retrievers.keys()
        if unknown:
            raise ValueError(
                f"Unknown retriever name(s): {sorted(unknown)}. Available retrievers: {sorted(self.retrievers.keys())}"
            )
        return {name: self.retrievers[name] for name in active_retrievers}

    def warm_up(self) -> None:
        """
        Warm up the retrievers if any has a warm_up method.
        """
        if self._is_warmed_up:
            return
        for retriever in self.retrievers.values():
            if hasattr(retriever, "warm_up") and callable(retriever.warm_up):
                retriever.warm_up()
        self._is_warmed_up = True

    @component.output_types(documents=list[Document])
    def run(
        self,
        query: str,
        filters: dict[str, Any] | None = None,
        top_k: int | None = None,
        *,
        active_retrievers: list[str] | None = None,
    ) -> dict[str, list[Document]]:
        """
        Runs retrievers in parallel on the given query and returns deduplicated results.

        :param query:
            The query to run the retrievers on.
        :param filters:
            The filters to apply to the retrievers. If not provided, the filters from the initialization of the
            component will be used. If those are also not provided, no filters will be applied.
        :param top_k:
            The number of documents to return per retriever. If not provided, the top_k from the initialization of
            the component will be used.
        :param active_retrievers:
            A list of retriever names to run. If not provided, all retrievers will be run.
            Names must match the keys provided in the `retrievers` dictionary at initialization.

        :returns:
            A dictionary with the keys:
                - "documents": A deduplicated list of retrieved documents.

        :raises ValueError:
            If any name in `active_retrievers` does not match a retriever name.
        """
        if not self._is_warmed_up:
            self.warm_up()

        resolved_top_k = top_k if top_k is not None else self.top_k
        resolved_filters = filters if filters is not None else self.filters

        retrievers_to_run = self._resolve_retrievers(active_retrievers)

        all_documents: list[Document] = []
        with ThreadPoolExecutor(max_workers=self.max_workers) as executor:
            future_to_name = {
                executor.submit(retriever.run, query=query, filters=resolved_filters, top_k=resolved_top_k): name
                for name, retriever in retrievers_to_run.items()
            }
            for future in as_completed(future_to_name):
                name = future_to_name[future]
                try:
                    all_documents.extend(future.result().get("documents", []))
                except Exception as e:
                    raise RuntimeError(f"Retriever '{name}' failed: {e}") from e

        return {"documents": _deduplicate_documents(all_documents)}

    @component.output_types(documents=list[Document])
    async def run_async(
        self,
        query: str,
        filters: dict[str, Any] | None = None,
        top_k: int | None = None,
        *,
        active_retrievers: list[str] | None = None,
    ) -> dict[str, list[Document]]:
        """
        Runs retrievers concurrently on the given query and returns deduplicated results.

        Uses each retriever's `run_async` method if available, otherwise runs `run` in a thread executor.

        :param query:
            The query to run the retrievers on.
        :param filters:
            The filters to apply to the retrievers. If not provided, the filters from the initialization of the
            component will be used. If those are also not provided, no filters will be applied.
        :param top_k:
            The number of documents to return per retriever. If not provided, the top_k from the initialization of
            the component will be used.
        :param active_retrievers:
            A list of retriever names to run. If not provided, all retrievers will be run.
            Names must match the keys provided in the `retrievers` dictionary at initialization.

        :returns:
            A dictionary with the keys:
                - "documents": A deduplicated list of retrieved documents.

        :raises ValueError:
            If any name in `active_retrievers` does not match a retriever name.
        """
        if not self._is_warmed_up:
            self.warm_up()

        resolved_top_k = top_k if top_k is not None else self.top_k
        resolved_filters = filters if filters is not None else self.filters

        retrievers_to_run = self._resolve_retrievers(active_retrievers)

        loop = asyncio.get_running_loop()

        async def _run_one(name: str, retriever: TextRetriever) -> list[Document]:
            try:
                if hasattr(retriever, "run_async") and callable(retriever.run_async):
                    result = await retriever.run_async(query=query, filters=resolved_filters, top_k=resolved_top_k)
                else:
                    result = await loop.run_in_executor(
                        None, lambda: retriever.run(query=query, filters=resolved_filters, top_k=resolved_top_k)
                    )
                return result.get("documents", [])
            except Exception as e:
                raise RuntimeError(f"Retriever '{name}' failed: {e}") from e

        results = await asyncio.gather(*[_run_one(name, r) for name, r in retrievers_to_run.items()])

        all_documents: list[Document] = []
        for docs in results:
            all_documents.extend(docs)

        return {"documents": _deduplicate_documents(all_documents)}

    def to_dict(self) -> dict[str, Any]:
        """
        Serializes the component to a dictionary.

        :returns:
            Dictionary with serialized data.
        """
        return default_to_dict(
            self,
            retrievers={name: component_to_dict(obj=r, name=name) for name, r in self.retrievers.items()},
            filters=self.filters,
            top_k=self.top_k,
            max_workers=self.max_workers,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MultiRetriever":
        """
        Creates an instance of the component from a dictionary.

        :param data:
            Dictionary with the data to create the component.
        """
        retrievers_data = data.get("init_parameters", {}).get("retrievers", {})
        if retrievers_data:
            retrievers = {}
            for name, retriever_data in retrievers_data.items():
                try:
                    imported_class = import_class_by_name(retriever_data["type"])
                except ImportError as e:
                    raise ImportError(
                        f"Could not import class {retriever_data['type']} for retriever '{name}'. Error: {str(e)}"
                    ) from e
                retrievers[name] = component_from_dict(cls=imported_class, data=retriever_data, name=name)
            data["init_parameters"]["retrievers"] = retrievers
        return default_from_dict(cls, data)
