# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any

from haystack import component, default_from_dict, default_to_dict
from haystack.components.retrievers.types.protocol import TextRetriever
from haystack.core.serialization import component_from_dict, component_to_dict, import_class_by_name
from haystack.dataclasses import Document
from haystack.utils.misc import _deduplicate_documents


@component
class MultiRetriever:
    """
    A component that runs multiple retrievers in parallel and combines their results.

    Each retriever is queried concurrently using a thread pool.
    The results are deduplicated and returned as a single list of documents.

    ### Usage example

    ```python
    from haystack import Document
    from haystack.document_stores.in_memory import InMemoryDocumentStore
    from haystack.document_stores.types import DuplicatePolicy
    from haystack.components.retrievers import InMemoryBM25Retriever, InMemoryEmbeddingRetriever
    from haystack.components.retrievers import QueryEmbeddingRetriever, MultiRetriever
    from haystack.components.embedders import SentenceTransformersTextEmbedder, SentenceTransformersDocumentEmbedder
    from haystack.components.writers import DocumentWriter

    documents = [
        Document(content="Renewable energy is energy that is collected from renewable resources."),
        Document(content="Solar energy is a type of green energy that is harnessed from the sun."),
        Document(content="Wind energy is another type of green energy that is generated by wind turbines."),
    ]

    # Populate the document store
    doc_store = InMemoryDocumentStore()
    doc_embedder = SentenceTransformersDocumentEmbedder(model="sentence-transformers/all-MiniLM-L6-v2")
    doc_writer = DocumentWriter(document_store=doc_store, policy=DuplicatePolicy.SKIP)
    doc_writer.run(documents=doc_embedder.run(documents)["documents"])

    # Run the multi-retriever
    retriever = MultiRetriever(
        retrievers=[
            InMemoryBM25Retriever(document_store=doc_store),
            QueryEmbeddingRetriever(
                retriever=InMemoryEmbeddingRetriever(document_store=doc_store),
                query_embedder=SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2"),
            ),
        ],
        top_k=3,
    )
    result = retriever.run(query="green energy sources")
    for doc in result["documents"]:
        print(doc.content)
    ```
    """

    def __init__(
        self,
        *,
        retrievers: list[TextRetriever],
        filters: dict[str, Any] | None = None,
        top_k: int = 10,
        max_workers: int = 4,
    ) -> None:
        """
        Create the MultiRetriever component.

        :param retrievers:
            A list of retriever components to run in parallel.
        :param filters:
            A dictionary of filters to apply when retrieving documents.
        :param top_k:
            The maximum number of documents to return per retriever.
        :param max_workers:
            The maximum number of threads to use for parallel retrieval.
        """
        self.retrievers = retrievers
        self.filters = filters
        self.top_k = top_k
        self.max_workers = max_workers
        self._is_warmed_up = False

    def warm_up(self) -> None:
        """
        Warm up the retrievers if any has a warm_up method.
        """
        if self._is_warmed_up:
            return
        for retriever in self.retrievers:
            if hasattr(retriever, "warm_up") and callable(retriever.warm_up):
                retriever.warm_up()
        self._is_warmed_up = True

    # TODO Could be nice to have a way of turning retrievers on and off at runtime.
    #      Not sure how to do this since we don't store any sort of name or id for the retrievers.
    #      Could make retrievers a dict instead of a list?
    @component.output_types(documents=list[Document])
    def run(
        self, query: str, filters: dict[str, Any] | None = None, top_k: int | None = None
    ) -> dict[str, list[Document]]:
        """
        Runs all retrievers in parallel on the given query and returns deduplicated results.

        :param query:
            The query to run the retrievers on.
        :param filters:
            The filters to apply to the retrievers. If not provided, the filters from the initialization of the
            component will be used. If those are also not provided, no filters will be applied.
        :param top_k:
            The number of documents to return per retriever. If not provided, the top_k from the initialization of
            the component will be used.

        :returns:
            A dictionary with the keys:
                - "documents": A deduplicated list of retrieved documents.
        """
        if not self._is_warmed_up:
            self.warm_up()

        resolved_top_k = top_k if top_k is not None else self.top_k
        resolved_filters = filters if filters is not None else self.filters

        all_documents: list[Document] = []
        with ThreadPoolExecutor(max_workers=self.max_workers) as executor:
            futures = {
                executor.submit(retriever.run, query=query, filters=resolved_filters, top_k=resolved_top_k)
                for retriever in self.retrievers
            }
            for future in as_completed(futures):
                all_documents.extend(future.result().get("documents", []))

        return {"documents": _deduplicate_documents(all_documents)}

    def to_dict(self) -> dict[str, Any]:
        """
        Serializes the component to a dictionary.

        :returns:
            Dictionary with serialized data.
        """
        return default_to_dict(
            self,
            retrievers=[component_to_dict(obj=r, name="retriever") for r in self.retrievers],
            filters=self.filters,
            top_k=self.top_k,
            max_workers=self.max_workers,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MultiRetriever":
        """
        Creates an instance of the component from a dictionary.

        :param data:
            Dictionary with the data to create the component.
        """
        retrievers_data = data.get("init_parameters", {}).get("retrievers", [])
        if retrievers_data:
            retrievers = []
            for retriever_data in retrievers_data:
                try:
                    imported_class = import_class_by_name(retriever_data["type"])
                except ImportError as e:
                    raise ImportError(
                        f"Could not import class {retriever_data['type']} for retriever. Error: {str(e)}"
                    ) from e
                retriever = component_from_dict(cls=imported_class, data=retriever_data, name="retriever")
                retrievers.append(retriever)
            data["init_parameters"]["retrievers"] = retrievers
        return default_from_dict(cls, data)
