FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    curl \
    gcc \
    git \
    libtesseract-dev \
    poppler-utils \
    tesseract-ocr

ARG XPDF_VERSION
RUN curl -O https://dl.xpdfreader.com/xpdf-${XPDF_VERSION}.tar.gz && \
    tar -xvf xpdf-${XPDF_VERSION}.tar.gz && \
    cd xpdf-${XPDF_VERSION} && \
    cmake . && \
    make && \
    cp xpdf/pdftotext /opt && \
    cd .. \
    rm -rf xpdf-${XPDF_VERSION}
