default_branch: main
collapse_pre_releases: true
pre_release_tag_re: (?P<pre_release>-(?:[ab]|rc)+\d*)$
prelude_section_name: ⭐ Highlights
template: |
  ---
  enhancements:
    - |
      Changed metadata to meta

sections:
  # The prelude section is implicitly included.
  - [upgrade, ⬆️ Upgrade Notes]
  - [features, 🚀 New Features]
  - [enhancements, ⚡️ Enhancement Notes]
  - [issues, Known Issues]
  - [deprecations, ⚠️ Deprecation Notes]
  - [security, Security Notes]
  - [fixes, 🐛 Bug Fixes]
