version: ignore

components:
- name: Retriever
  params:
    api_key: RETRIEVER_PARAMS_API_KEY
  type: WebRetriever
- name: Shaper
  params:
    func: join_documents_and_scores
    inputs:
      documents: documents
    outputs:
    - documents
  type: Shaper
- name: custom-at-query-time
  params:
    prompt: "\nSynthesize a comprehensive answer from the following most relevant\
      \ paragraphs and the given question.\nProvide a clear and concise response that\
      \ summarizes the key points and information presented in the paragraphs.\nYour\
      \ answer should be in your own words and be no longer than 50 words.\n\n\n Paragraphs:\
      \ {documents} \n\n Question: {query} \n\n Answer:\n"
  type: PromptTemplate
- name: PromptNode
  params:
    api_key: PROMPTNODE_PARAMS_API_KEY
    default_prompt_template: custom-at-query-time
    max_length: 256
    model_name_or_path: gpt-3.5-turbo
  type: PromptNode
pipelines:
- name: query
  nodes:
  - inputs:
    - Query
    name: Retriever
  - inputs:
    - Retriever
    name: Shaper
  - inputs:
    - Shaper
    name: PromptNode
