# Dummy pipeline, used when the CI needs to load the REST API to extract the OpenAPI specs. DO NOT USE.
version: ignore

components:
  - name: FileTypeClassifier
    type: FileTypeClassifier

pipelines:
  - name: query
    nodes:
      - name: FileTypeClassifier
        inputs: [File]

  - name: indexing
    nodes:
      - name: FileTypeClassifier
        inputs: [File]
