# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

import os
from typing import Any, ClassVar

from openai import AsyncOpenAI, OpenAI

from haystack import component, default_from_dict, default_to_dict
from haystack.components.generators.chat import OpenAIChatGenerator
from haystack.dataclasses.streaming_chunk import StreamingCallbackT
from haystack.tools import (
    ToolsType,
    _check_duplicate_tool_names,
    deserialize_tools_or_toolset_inplace,
    flatten_tools_or_toolsets,
    serialize_tools_or_toolset,
    warm_up_tools,
)
from haystack.utils import Secret, deserialize_callable, serialize_callable
from haystack.utils.http_client import init_http_client

MINIMAX_DEFAULT_BASE_URL = "https://api.minimax.io/v1"


@component
class MiniMaxChatGenerator(OpenAIChatGenerator):
    """
    Completes chats using MiniMax's large language models (LLMs).

    It uses MiniMax's OpenAI-compatible API and supports streaming responses.
    It uses [ChatMessage](https://docs.haystack.deepset.ai/docs/chatmessage)
    format in input and output.

    You can customize how the text is generated by passing parameters to the
    MiniMax API. Use the `**generation_kwargs` argument when you initialize
    the component or when you run it.

    ### Usage example
    ```python
    from haystack.components.generators.chat import MiniMaxChatGenerator
    from haystack.dataclasses import ChatMessage

    messages = [ChatMessage.from_user("What's Natural Language Processing?")]

    client = MiniMaxChatGenerator()
    response = client.run(messages)
    print(response)
    ```
    """

    SUPPORTED_MODELS: ClassVar[list[str]] = [
        "MiniMax-M2.7",
        "MiniMax-M2.7-highspeed",
    ]
    """MiniMax chat models supported by this component.
    See https://platform.minimax.io/docs/api-reference/text-openai-api for details."""

    def __init__(
        self,
        api_key: Secret = Secret.from_env_var("MINIMAX_API_KEY"),
        model: str = "MiniMax-M2.7",
        streaming_callback: StreamingCallbackT | None = None,
        api_base_url: str | None = None,
        organization: str | None = None,
        generation_kwargs: dict[str, Any] | None = None,
        timeout: float | None = None,
        max_retries: int | None = None,
        tools: ToolsType | None = None,
        tools_strict: bool = False,
        http_client_kwargs: dict[str, Any] | None = None,
    ) -> None:
        """
        Initialize the MiniMax Chat Generator component.

        :param api_key: The MiniMax API key. Set via the `MINIMAX_API_KEY` environment variable.
        :param model: The name of the MiniMax model to use. Defaults to `MiniMax-M2.7`.
        :param streaming_callback: A callback function called when a new token is received from the stream.
            It accepts [StreamingChunk](https://docs.haystack.deepset.ai/docs/data-classes#streamingchunk)
            as an argument.
        :param api_base_url: An optional base URL. Defaults to `https://api.minimax.io/v1`.
        :param organization: Your organization ID, defaults to `None`.
        :param generation_kwargs: Other parameters to use for the model. These parameters are sent directly to
            the MiniMax endpoint. Some supported parameters:
            - `max_tokens`: An upper bound for the number of tokens to generate.
            - `temperature`: Sampling temperature in the range (0.0, 1.0]. Defaults to 1.0.
            - `top_p`: Nucleus sampling probability mass.
            - `n`: Number of completions to generate for each prompt.
            - `stop`: One or more sequences after which the model stops generating tokens.
        :param timeout: Timeout for API calls. Defaults to 30 seconds.
        :param max_retries: Maximum number of retries after an internal error. Defaults to 5.
        :param tools: A list of Tool and/or Toolset objects for which the model can prepare calls.
        :param tools_strict: Whether to enable strict schema adherence for tool calls.
        :param http_client_kwargs: A dictionary of keyword arguments to configure a custom httpx client.
        """
        # We intentionally do not call super().__init__ here because the @component decorator
        # rewrites the class hierarchy, which breaks super() when both parent and child are
        # decorated with @component. Instead, we initialize all attributes directly, mirroring
        # the approach taken by AzureOpenAIChatGenerator.

        self.api_key = api_key
        self.model = model
        self.generation_kwargs = generation_kwargs or {}
        self.streaming_callback = streaming_callback
        self.api_base_url = api_base_url
        self.organization = organization
        self.timeout = timeout
        self.max_retries = max_retries
        self.tools = tools
        self.tools_strict = tools_strict
        self.http_client_kwargs = http_client_kwargs
        _check_duplicate_tool_names(flatten_tools_or_toolsets(self.tools))

        resolved_timeout = timeout if timeout is not None else float(os.environ.get("OPENAI_TIMEOUT", "30.0"))
        resolved_max_retries = max_retries if max_retries is not None else int(os.environ.get("OPENAI_MAX_RETRIES", "5"))
        resolved_base_url = api_base_url or MINIMAX_DEFAULT_BASE_URL

        client_kwargs: dict[str, Any] = {
            "api_key": api_key.resolve_value(),
            "organization": organization,
            "base_url": resolved_base_url,
            "timeout": resolved_timeout,
            "max_retries": resolved_max_retries,
        }

        self.client = OpenAI(http_client=init_http_client(self.http_client_kwargs, async_client=False), **client_kwargs)
        self.async_client = AsyncOpenAI(
            http_client=init_http_client(self.http_client_kwargs, async_client=True), **client_kwargs
        )
        self._is_warmed_up = False

    def warm_up(self) -> None:
        """
        Warm up the MiniMax chat generator.

        This will warm up the tools registered in the chat generator.
        This method is idempotent and will only warm up the tools once.
        """
        if not self._is_warmed_up:
            warm_up_tools(self.tools)
            self._is_warmed_up = True

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize this component to a dictionary.

        :returns:
            The serialized component as a dictionary.
        """
        callback_name = serialize_callable(self.streaming_callback) if self.streaming_callback else None
        return default_to_dict(
            self,
            model=self.model,
            streaming_callback=callback_name,
            api_base_url=self.api_base_url,
            organization=self.organization,
            generation_kwargs=self.generation_kwargs,
            api_key=self.api_key,
            timeout=self.timeout,
            max_retries=self.max_retries,
            tools=serialize_tools_or_toolset(self.tools),
            tools_strict=self.tools_strict,
            http_client_kwargs=self.http_client_kwargs,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "MiniMaxChatGenerator":
        """
        Deserialize this component from a dictionary.

        :param data: The dictionary representation of this component.
        :returns:
            The deserialized component instance.
        """
        deserialize_tools_or_toolset_inplace(data["init_parameters"], key="tools")
        init_params = data.get("init_parameters", {})
        serialized_callback_handler = init_params.get("streaming_callback")
        if serialized_callback_handler:
            data["init_parameters"]["streaming_callback"] = deserialize_callable(serialized_callback_handler)
        return default_from_dict(cls, data)
