from tests.nodes.test_accumulate import Accumulate
from tests.nodes.test_add_value import AddValue
from tests.nodes.test_below import Below
from tests.nodes.test_double import Double
from tests.nodes.test_greet import Greet
from tests.nodes.test_merge import Merge
from tests.nodes.test_remainder import Remainder
from tests.nodes.test_rename import Rename
from tests.nodes.test_repeat import Repeat
from tests.nodes.test_subtract import Subtract
from tests.nodes.test_sum import Sum
