name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    steps:
      - uses: actions/checkout@v2
      - name: Test with mypy
          run: |
            pip install mypy
            mypy haystack --ignore-missing-imports

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test-path:
          - test_document_store.py
          - test_docx_conversion.py
          - test_dpr_retriever.py
          - test_dummy_retriever.py
          - test_elastic_dsl_convertor.py
          - test_elastic_retriever.py
          - test_embedding_retriever.py
          - test_eval.py
          - test_faiss_and_milvus.py
          - test_finder.py
          - test_generator.py
          - test_imports.py
          - test_pdf_conversion.py
          - test_pipeline.py
          - test_preprocessor.py
          - test_reader.py
          - test_rest_api.py
          - test_summarizer.py
          - test_tfidf_retriever.py
          - test_utils.py
    steps:
    - uses: actions/checkout@v2
      
    - name: Run Elasticsearch
      run: docker run -d -p 9200:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" elasticsearch:7.9.2

    - name: Run Milvus
      run: docker run -d -p 19530:19530 -p 19121:19121 milvusdb/milvus:0.10.5-cpu-d010621-4eda95

    - name: Run Apache Tika
      run: docker run -d -p 9998:9998 -e "TIKA_CHILD_JAVA_OPTS=-JXms128m" -e "TIKA_CHILD_JAVA_OPTS=-JXmx128m" apache/tika:1.24.1

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .
        wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.03.tar.gz && tar -xvf xpdf-tools-linux-4.03.tar.gz && sudo cp xpdf-tools-linux-4.03/bin64/pdftotext /usr/local/bin

    - name: Run tests
      run: cd test && pytest ${{ matrix.test-path }}
