name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure sysctl limits for Elasticsearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      
    - name: Run Elasticsearch
      run: docker run -d -p 9200:9200 -e "discovery.type=single-node" -e 'ES_JAVA_OPTS=-Xms750m -Xmx750m' elasticsearch:7.9.2

    - name: Run Apache Tika
      run: docker run -d -p 9998:9998 apache/tika:1.24.1

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .
    
    - name: Test with pytest
      run: cd test && pytest

    - name: Test with mypy
      run: |
        pip install mypy
        mypy haystack --ignore-missing-imports
