name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure sysctl limits for Elasticsearch
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
      
    - name: Run Elasticsearch
      run: docker run --rm --env node.name=es1 --env cluster.name=docker-elasticsearch \
      --env cluster.initial_master_nodes=es1 --env discovery.seed_hosts=es1 \
      --env cluster.routing.allocation.disk.threshold_enabled=false --env bootstrap.memory_lock=true \
      --env 'ES_JAVA_OPTS=-Xms500m -Xmx500m' --env xpack.security.enabled=false --env xpack.license.self_generated.type=basic \
      --ulimit nofile=65536:65536 --ulimit memlock=-1:-1 --publish 9200:9200 --detach --network=elastic --name=es1 \
      docker.elastic.co/elasticsearch/elasticsearch:7.9.2

    - name: Run Apache Tika
      run: docker run -d -p 9998:9998 apache/tika:1.24.1

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
        pip install -e .
    
    - name: Test with pytest
      run: cd test && pytest

    - name: Test with mypy
      run: |
        pip install mypy
        mypy haystack --ignore-missing-imports
