name: CI Metrics

on:
  workflow_run:
    workflows:
      - "end-to-end"
      - "Tests"
      - "Slow Integration Tests"
    types:
      - completed
  pull_request:
    types:
      - opened
      - closed
jobs:
  send:
    runs-on: ubuntu-slim
    steps:
      - uses: int128/datadog-actions-metrics@bb2bfb0ab9ebbf1cb1b66c891f3cd2528e21fede # v1.165.0
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          datadog-site: "datadoghq.eu"
          collect-job-metrics: true
