name: CI Metrics

on:
  workflow_run:
    workflows:
      - "end-to-end"
      - "Tests"
      - "Slow Integration Tests"
    types:
      - completed
  pull_request:
    types:
      - opened
      - closed
jobs:
  send:
    runs-on: ubuntu-slim
    steps:
      - uses: int128/datadog-actions-metrics@46d3f0ae7393a3763b7f135f8721d89d924f3aed # v1.158.0
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          datadog-site: "datadoghq.eu"
          collect-job-metrics: true
