name: Compliance Checks

on:
  push:
    paths-ignore:
      - 'pyproject.toml'

jobs:
  check-license-compliance:
    name: Check license compliance
    runs-on: ubuntu-latest
    steps:
      - run: echo "Not required"
