name: Add comment about test coverage to PRs

on:
  workflow_run:
    workflows:
      - "Tests"
    types: [completed]

jobs:
  comment:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: py-cov-action/python-coverage-comment-action@63f52f4fbbffada6e8dee8ec432de7e01df9ba79 # v3.41
        with:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 60
