name: Deploy website

# Controls when the action will run. Triggers the workflow on push 
# events but only for the master branch
on:
  push:
    branches: [ master, benchmarks, automate_docstrings ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:

      # Generates the docstrings and tutorials so that we have the latest for the deployment
      - name: Generate Docstrings and Tutorials
        run: |
          sudo apt update
          sudo apt install python3-pip
          pip3 install 'pydoc-markdown>=3.0.0,<4.0.0'
          pip3 install jupytercontrib
          cd docs/_src/api/api/
          .generate_docstrings.sh 
          cd ../../tutorials/tutorials/
          python3 convert_ipynb.py 

      # Creates dispatch event for haystack-website repo
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PUBLIC_REPO_ACCESS_TOKEN }}
          repository: deepset-ai/haystack-website
          event-type: deploy-website
          client-payload: '{}'
