name: docker-build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            repository: arzelaascoli/haystack-cpu
            tagprefix: ''
            latest: true

          - dockerfile: Dockerfile-GPU
            repository: arzelaascoli/haystack-gpu
            tagprefix: 'demo-'
            latest: true

          - dockerfile: Dockerfile-GPU-minimal
            repository: arzelaascoli/haystack-gpu
            tagprefix: 'minimal-'
            latest: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ matrix.repository }}
          flavor: |
            prefix=${{ matrix.tagprefix }}
          tags: |
            type=ref,event=tag                    
            type=sha,format=long
            type=raw,value=latest
            type=raw,value=latest,prefix=,enable=${{ matrix.latest }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          cache-from: type=registry,ref=${{ matrix.repository }}:latest
          cache-to: type=inline
