name: run docstrings linting

on:
  push:
    branches:
      - docstrings-linting

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch==${{ env.HATCH_VERSION }}

      - name: Pylint
        run: |
         hatch run test:lint
