name: run docstrings linting

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths:
      - "**.py"

env:
  HATCH_VERSION: "1.13.0"

jobs:
  docstrings-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch==${{ env.HATCH_VERSION }}

      - name: ruff docstrings linting
        run: hatch run ruff check haystack
