# If you change this name also do it in ci_metrics.yml
name: end-to-end

on:
  workflow_dispatch: # Activate this workflow manually
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "e2e/**/*.py"
      - ".github/workflows/e2e.yml"

env:
  PYTHON_VERSION: "3.10"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  HATCH_VERSION: "1.16.5"
  # we use HF_TOKEN instead of HF_API_TOKEN to work around a Hugging Face bug
  # see https://github.com/deepset-ai/haystack/issues/9552
  HF_TOKEN: ${{ secrets.HUGGINGFACE_API_KEY }}

jobs:
  run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "${{ env.PYTHON_VERSION }}"

    - name: Install Hatch
      run: pip install hatch==${{ env.HATCH_VERSION }}

    - name: Run tests
      run: hatch run e2e:test

    - name: Notify Slack on nightly failure
      if: failure() && github.event_name == 'schedule'
      uses: deepset-ai/notify-slack-action@3cda73b77a148f16f703274198e7771340cf862b # v1
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NOTIFICATIONS }}
