name: Examples tests

on:
  workflow_dispatch: # Activate this workflow manually
  push:
    branches:
      - main
  pull_request:
    paths:
      - examples/**
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  PYTHON_VERSION: "3.8"

jobs:
  tests:
      name: Examples
      runs-on: ubuntu-latest
      services:
        elasticsearch:
          image: elasticsearch:7.17.6
          env:
            discovery.type: "single-node"
            ES_JAVA_OPTS: "-Xms128m -Xmx256m"
          ports:
            - 9200:9200

      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v4
          with:
            python-version: ${{ env.PYTHON_VERSION }}

        - name: Install Haystack
          run: pip install .[all]

        - name: Run
          run: pytest examples/

        - uses: slackapi/slack-github-action@v1.23.0
          if: failure() && github.ref == 'refs/heads/main'
          with:
            payload: |
              {
                "text": ":x: Job ${{ env.GITHUB_JOB }} failed for ${{ github.ref_type }} ${{ github.ref_name }}",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": ":x: Job ${{ env.GITHUB_JOB }} failed for ${{ github.ref_type }} ${{ github.ref_name }}",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Click *<https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}|here>* for more details "
                    }
                  }
                ]
              }
