name: formatting_check

on: [push, pull_request]

jobs:
  formatting_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: shell_check
      run: .github/workflows/shell_check.sh
