name: Generate JSON Schema

on:
  workflow_dispatch:

jobs:
  generate-json-schema:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-json-schema.txt') }}-generate-json-schema
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install .
          pip install -r requirements-json-schema.txt
      - name: Generate JSON Schema
        run: python ./.github/utils/generate_json_schema.py
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
