name: Linux CI

on:
  workflow_dispatch:
  push:

jobs:

  build-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Cache
        id: cache-python-env
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          # The cache currently misses at every change in the Python files to ensure
          # that the code changes to Haystack are not being cached along with the dependencies.
          # TODO for the tests refactoring: We could speed up the process by caching only 
          # the dependencies and installing Haystack again separately for each test runner.
          key: linux-${{ hashFiles('**/*.py') }}-${{ hashFiles('**/setup.cfg') }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github') }}

      - name: Install dependencies
        if: steps.cache-python-env.outputs.cache-hit != 'true'
        run: |
          pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager .[test]
          pip install --upgrade --upgrade-strategy eager rest_api/
          pip install --upgrade --upgrade-strategy eager ui/
          pip install black[jupyter] "pydoc-markdown>=4,<5" mkdocs jupytercontrib watchdog==1.0.2
          pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cpu.html

  prepare-build:
    needs: build-cache
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(find $(find . -type d -name test -not -path "./*env*/*") -type f -name test_*.py | jq -SR . | jq -cs .)"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  code-and-docs-updates:
    needs: build-cache
    runs-on: ubuntu-latest
    if: ${{ "master" not in github.ref }}

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Cache Python
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: linux-${{ hashFiles('**/*.py') }}-${{ hashFiles('**/setup.cfg') }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github') }}
          
      # Apply black on the entire codebase
      - name: Blacken
        run: python3 -m black .

      # Convert the Jupyter notebooks into markdown tutorials
      - name: Generate Tutorials
        run: |
          cd docs/_src/tutorials/tutorials/
          python3 convert_ipynb.py

      # Generate markdown files from the docstrings with pydoc-markdown
      - name: Generate Docstrings
        run: |
          set -e   # Fails on any error in the following loop
          cd docs/_src/api/api/
          for file in ../pydoc/* ; do
            echo "Processing" $file
            pydoc-markdown "$file"
          done

      # Generates the OpenAPI specs file to be used on the documentation website
      - name: Generate OpenAPI Specs
        run: |
          cd docs/_src/api/openapi/
          python generate_openapi_specs.py

      # Generates a new JSON schema for the pipeline YAML validation
      - name: Generate JSON schema for pipelines
        run: python ./.github/utils/generate_json_schema.py
      
      # Commit the files to GitHub
      - name: Commit files
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          echo ""
          echo "============= Documentation changes ============="
          git add docs/_src/api/api/
          git commit -m "Update Documentation" -a || echo "No documentation changes to commit"

          echo ""
          echo "============= API Specs changes: ============="
          git add docs/_src/api/openapi/
          git commit -m "Update OpenAPI specs" -a || echo "No API specification changes to commit"
          
          echo ""
          echo "============= JSON schema changes: ============="
          git add json-schemas/
          git commit -m "Update JSON schema" -a || echo "No JSON schema changes to commit"

          echo ""
          echo "============= Code Style (Black): ============="
          git add .
          git commit -m "Apply Black" -a || echo "No code changes to commit"

          echo ""
          echo "============= Summary: ============="
          git status
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  type-check:
    needs: code_and_docs_updates
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run:  pip install mypy types-Markdown types-requests types-PyYAML pydantic

      - name: Test with mypy
        run: mypy haystack

  build:
    needs: prepare-build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test-path: ${{fromJson(needs.prepare-build.outputs.matrix)}}
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Cache Python
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: linux-${{ hashFiles('**/*.py') }}-${{ hashFiles('**/setup.cfg') }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github') }}

    - name: Run Elasticsearch
      run: docker run -d -p 9200:9200 -e "discovery.type=single-node" -e "ES_JAVA_OPTS=-Xms128m -Xmx128m" elasticsearch:7.9.2

    - name: Run Milvus
      run: docker run -d -p 19530:19530 -p 19121:19121 milvusdb/milvus:1.1.0-cpu-d050721-5e559c

    - name: Run Weaviate
      run: docker run -d -p 8080:8080 --name haystack_test_weaviate --env AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED='true' --env PERSISTENCE_DATA_PATH='/var/lib/weaviate' semitechnologies/weaviate:1.7.2

    - name: Run GraphDB
      run: docker run -d -p 7200:7200 --name haystack_test_graphdb deepset/graphdb-free:9.4.1-adoptopenjdk11

    - name: Run Apache Tika
      run: docker run -d -p 9998:9998 -e "TIKA_CHILD_JAVA_OPTS=-JXms128m" -e "TIKA_CHILD_JAVA_OPTS=-JXmx128m" apache/tika:1.24.1

    - name: Run Parsr
      run: docker run -d -p 3001:3001 axarev/parsr:v1.2.2

#    - name: Run Ray
#      run: RAY_DISABLE_MEMORY_MONITOR=1 ray start --head

    - name: Install pdftotext
      run: wget --no-check-certificate https://dl.xpdfreader.com/xpdf-tools-linux-4.03.tar.gz && tar -xvf xpdf-tools-linux-4.03.tar.gz && sudo cp xpdf-tools-linux-4.03/bin64/pdftotext /usr/local/bin

    - name: Install tesseract
      run: sudo apt-get install tesseract-ocr libtesseract-dev poppler-utils

    - name: Run tests
      run: pytest -s ${{ matrix.test-path }}
