name: Trigger preview release

on:
  push:
    branches:
      - main
    paths:
      - "haystack/preview/**.py"

jobs:
  release-on-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger preview release
        env:
          HAYSTACK_BOT_REPO_DISPATCH_PA_TOKEN: ${{ secrets.HAYSTACK_BOT_REPO_DISPATCH_PA_TOKEN }}
        run: |
          curl -L \
            -X POST \
            -H "Authorization: Bearer $HAYSTACK_BOT_REPO_DISPATCH_PA_TOKEN" \
            https://api.github.com/repos/deepset-ai/haystack-preview-package/dispatches \
            -d '{"event_type":"preview_release"}'
