name: Testing Haystack-Readme integration

on:
  push:
    branches:
      - readme_integration_api

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Generate API docs
        run: ./.github/utils/pydoc-markdown.sh

      - name: Github Action (API sync)
        uses: readmeio/rdme@7.2.0
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
        with:
          rdme: docs ./docs/_src/api/api --key="$README_API_KEY" --version=1.8-latest
