# If you change this name also do it in slow.yml and ci_metrics.yml
name: Slow Integration Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      # Keep the list in sync with the paths defined in the `slow.yml` workflow and below in this file
      - "haystack/components/audio/whisper_local.py"
      - "haystack/components/converters/tika.py"
      - "test/components/audio/test_whisper_local.py"
      - "test/components/converters/test_tika_doc_converter.py"

jobs:

  check_if_changed:
    name: Check if changed
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code_changes: ${{ steps.changes.outputs.code_changes }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changed code
        id: changes
        uses: dorny/paths-filter@v3
        with:
          # keep the list in sync with the paths defined in the `slow.yml` workflow and above in this file
          filters: |
            code_changes:
              - "haystack/components/audio/whisper_local.py"
              - "haystack/components/converters/tika.py"
              - "test/components/audio/test_whisper_local.py"
              - "test/components/converters/test_tika_doc_converter.py"

  trigger-catch-all:
    name: Slow Integration Tests completed
    needs: check_if_changed
    if: needs.check_if_changed.outputs.code_changes == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Mark tests as completed
        run: |
          echo "Slow Integration Tests skipped!"
