name: 'Stalebot'
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  makestale:
    runs-on: ubuntu-slim
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          any-of-labels: 'proposal,information-needed'
          stale-pr-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          days-before-stale: 30
          days-before-close: 10
