name: Github workflows linter

on:
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  lint-workflows:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ">=1.24.0"

      - name: Install actionlint
        run: go install github.com/rhysd/actionlint/cmd/actionlint@latest

      - name: Run actionlint
        env:
          SHELLCHECK_OPTS: --exclude=SC2102
        run: actionlint
