name: Xpdf Docker image release

on:
  push:
    branches:
      - main
    paths:
      - docker/docker-bake-xpdf.hcl
      - docker/Dockerfile.xpdf

jobs:
  publish-xpdf-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_NAME: deepset/xpdf

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and publish Xpdf image
        uses: docker/bake-action@v2
        with:
          files: "docker-bake-xpdf.hcl"
          workdir: docker
          targets: xpdf
          push: true
